{% set name = "pkgconfig" %}
{% set version = "1.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pkgconfig-{{ version }}.tar.gz
  sha256: 97bfe3d981bab675d5ea3ef259045d7919c93897db7d3b59d4e8593cba8d354f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pkg-config  # [unix]
  host:
    - python
    - poetry >=0.12
    - pip
  run:
    - python
    - m2w64-pkg-config  # [win and py27]
    - pkg-config  # [not(win and py27)]

test:
  imports:
    - pkgconfig

about:
  home: https://github.com/matze/pkgconfig
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python interface to the pkg-config command line tool

extra:
  recipe-maintainers:
    - jakirkham
    - lbdreyer
    - ocefpaf
    - tdegeus
