{% set version = "1.5.5" %}

package:
  name: pkgconfig
  version: {{ version }}

source:
  url: https://github.com/matze/pkgconfig/archive/v{{ version }}.tar.gz
  sha256: 58ee1926b23ddb766a55eb9932441201a60e8e476d3798d0c5def167604f3b6c

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pkg-config  # [unix]
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - m2w64-pkg-config  # [win and py27]
    - pkg-config  # [not(win and py27)]

test:
  imports:
    - pkgconfig

about:
  home: https://github.com/matze/pkgconfig
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python interface to the pkg-config command line tool

extra:
  recipe-maintainers:
    - jakirkham
    - lbdreyer
    - ocefpaf
    - tdegeus
