{% set version = "1.5.5" %}

package:
  name: pkgconfig
  version: {{ version }}

source:
  url: https://github.com/matze/pkgconfig/archive/v{{ version }}.tar.gz
  sha256: 58ee1926b23ddb766a55eb9932441201a60e8e476d3798d0c5def167604f3b6c

build:
  number: 5
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }}
    - pkg-config

test:
  requires:
    - python {{ python_min }}
  imports:
    - pkgconfig

about:
  home: https://github.com/matze/pkgconfig
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python interface to the pkg-config command line tool

extra:
  recipe-maintainers:
    - jakirkham
    - lbdreyer
    - ocefpaf
    - tdegeus
