{% set version = "1.5.1" %}

package:
  name: pkgconfig
  version: {{ version }}

source:
  url: https://github.com/matze/pkgconfig/archive/v{{ version }}.tar.gz
  sha256: 88d9ef0c4fee5f760b9ab500d94ef363644340e09f66481e36eb9275fce7a2f9

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - pkg-config        # [unix]
  host:
    - python
    - pip
    - poetry >=0.12
  run:
    - python
    - m2w64-pkg-config  # [win]

test:
  imports:
    - pkgconfig

about:
  home: https://github.com/matze/pkgconfig
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Python interface to the pkg-config command line tool'

extra:
  recipe-maintainers:
    - jakirkham
    - lbdreyer
    - ocefpaf
