{% set version = "1.5.4" %}

package:
  name: pkgconfig
  version: {{ version }}

source:
  url: https://github.com/matze/pkgconfig/archive/v{{ version }}.tar.gz
  sha256: 10795edee41f7f4a0cc35a0ab64403316907f3256aade8c9a106f6498c8d95b3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pkg-config  # [unix]
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - m2w64-pkg-config  # [win and py27]
    - pkg-config  # [not(win and py27)]

test:
  imports:
    - pkgconfig

about:
  home: https://github.com/matze/pkgconfig
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python interface to the pkg-config command line tool

extra:
  recipe-maintainers:
    - jakirkham
    - lbdreyer
    - ocefpaf
    - tdegeus
